version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.2-browsers

    steps:
    - checkout

    - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
    - run: sudo docker-php-ext-install zip

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "composer.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

    - save_cache:
        paths:
        - ./vendor
        key: v1-dependencies-{{ checksum "composer.json" }}

    # run tests!
    - run: ./vendor/bin/phpunit